### ISSUE TITLE
Home Page: Wording Correction

### ISSUE THREAD

**Issue by skrenek** [ZyMoEntertainment/Zymo.io#77]
Home page, latest products section, Flow One
- [x] Change Heading to "Flow One"
- [x] Change paragraph to:  `eSynchrony is a new platform for creating interactive visual communication. With it, medical professionals will be able to synchronize patient care among all staff departments. Together, Zymo and Flow One developed this innovative new software. Our initial market tests yield a reduction of patient wait times by 25-50%. We're excited to watch this technology increase productivity among health care professionals while also improving patients’ experiences at the same time.`

**Comment by CollinHerber** [comment]
Pull request in for it
